apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: profilestore
spec:
  type: state.in-memory
  version: v1
scopes:
- fairspot-profile
# Smoke-test only. State is not persisted across restarts.
