apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reportingstore
spec:
  type: state.in-memory
  version: v1
scopes:
- fps-reporting
# Smoke-test only. State is not persisted across restarts.
