server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: fairspot-identity
    static_configs:
      - targets:
          - localhost
        labels:
          environment: local
          source: local-harness
          service: identity
          __path__: /logs/local-harness/identity.log

  - job_name: fairspot-dapr
    static_configs:
      - targets:
          - localhost
        labels:
          environment: local
          source: local-harness
          service: dapr-run
          __path__: /logs/local-harness/dapr-run.log
