/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                    status?: string;
                    pageSize?: number | string;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetMyBookingsResponse"];
                        "application/json": components["schemas"]["GetMyBookingsResponse"];
                        "text/json": components["schemas"]["GetMyBookingsResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubmitBookingRequest"];
                    "text/json": components["schemas"]["SubmitBookingRequest"];
                    "application/*+json": components["schemas"]["SubmitBookingRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SubmitBookingResponse"];
                        "application/json": components["schemas"]["SubmitBookingResponse"];
                        "text/json": components["schemas"]["SubmitBookingResponse"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SubmitBookingResponse"];
                        "application/json": components["schemas"]["SubmitBookingResponse"];
                        "text/json": components["schemas"]["SubmitBookingResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: {
                    reason?: string;
                };
                header?: never;
                path: {
                    requestId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{requestId}/confirm-usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    requestId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConfirmUsageRequest"];
                    "text/json": components["schemas"]["ConfirmUsageRequest"];
                    "application/*+json": components["schemas"]["ConfirmUsageRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ConfirmUsageResponse"];
                        "application/json": components["schemas"]["ConfirmUsageResponse"];
                        "text/json": components["schemas"]["ConfirmUsageResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{requestId}/manual-corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    requestId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ManualCorrectionRequest"];
                    "text/json": components["schemas"]["ManualCorrectionRequest"];
                    "application/*+json": components["schemas"]["ManualCorrectionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ManualCorrectionResult"];
                        "application/json": components["schemas"]["ManualCorrectionResult"];
                        "text/json": components["schemas"]["ManualCorrectionResult"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draws/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TriggerDrawRequest"];
                    "text/json": components["schemas"]["TriggerDrawRequest"];
                    "application/*+json": components["schemas"]["TriggerDrawRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TriggerDrawResponse"];
                        "application/json": components["schemas"]["TriggerDrawResponse"];
                        "text/json": components["schemas"]["TriggerDrawResponse"];
                    };
                };
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TriggerDrawResponse"];
                        "application/json": components["schemas"]["TriggerDrawResponse"];
                        "text/json": components["schemas"]["TriggerDrawResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draws/{date}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    locationId?: string;
                    timeSlotStart?: string;
                    timeSlotEnd?: string;
                };
                header?: never;
                path: {
                    date: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DrawStatusResponse"];
                        "application/json": components["schemas"]["DrawStatusResponse"];
                        "text/json": components["schemas"]["DrawStatusResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/no-show-evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NoShowEvaluationRequest"];
                    "text/json": components["schemas"]["NoShowEvaluationRequest"];
                    "application/*+json": components["schemas"]["NoShowEvaluationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EvaluateNoShowResult"];
                        "application/json": components["schemas"]["EvaluateNoShowResult"];
                        "text/json": components["schemas"]["EvaluateNoShowResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BookingListItem: {
            /** Format: uuid */
            requestId: string;
            /** Format: date */
            requestedDate: string;
            /** Format: time */
            timeSlotStart: string;
            /** Format: time */
            timeSlotEnd: string;
            locationId: null | string;
            status: string;
            reason: null | string;
            allocatedSlotId: null | string;
            nextAction: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastStatusChangedAt: string;
        };
        ConfirmUsageRequest: {
            confirmationSource: string;
            /** Format: date-time */
            confirmedAt?: null | string;
            sourceEventId?: null | string;
            reason?: null | string;
        };
        ConfirmUsageResponse: {
            /** Format: uuid */
            requestId: string;
            status: string;
            /** Format: date-time */
            confirmedAt: string;
            wasAlreadyConfirmed: boolean;
        };
        DrawStatusResponse: {
            drawKey: string;
            status: string;
            /** Format: int32 */
            requestCount: number | string;
            /** Format: int32 */
            allocatedCount: number | string;
            /** Format: int32 */
            rejectedCount: number | string;
            /** Format: int32 */
            waitlistedCount: number | string;
            /** Format: int32 */
            companyCarOverflowCount: number | string;
            summaryRejectionReasons: string[];
            algorithmVersion: string;
            /** Format: int64 */
            seed: number | string;
            auditReference: null | string;
            /** Format: date-time */
            startedAt: null | string;
            /** Format: date-time */
            completedAt: null | string;
        };
        EvaluateNoShowResult: {
            /** Format: int32 */
            markedCount: number | string;
            /** Format: int32 */
            skippedCount: number | string;
            skippedReason: null | string;
        };
        GetMyBookingsResponse: {
            items: components["schemas"]["BookingListItem"][];
            nextCursor: null | string;
        };
        ManualCorrectionRequest: {
            correctionType: string;
            oldValue: string;
            newValue: string;
            reason: string;
            /** Format: date-time */
            effectiveAt?: null | string;
        };
        ManualCorrectionResult: {
            /** Format: uuid */
            requestId: string;
            correctionType: string;
            newValue: string;
            /** Format: date-time */
            appliedAt: string;
        };
        NoShowEvaluationRequest: {
            locationId: string;
            /** Format: date */
            date: string;
            /** Format: date-time */
            timeSlotStart: string;
            /** Format: date-time */
            timeSlotEnd: string;
            reason: string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        SubmitBookingRequest: {
            facilityId: string;
            locationId: null | string;
            licensePlate: string;
            vehicleType: string;
            isElectric: boolean;
            requiresAccessibleSpot: boolean;
            isCompanyCar: boolean;
            /** Format: date-time */
            plannedArrivalTime: string;
            /** Format: date-time */
            plannedDepartureTime: string;
        };
        SubmitBookingResponse: {
            /** Format: uuid */
            requestId: string;
            status: string;
            rejectionCode: null | string;
            reason: null | string;
        };
        TriggerDrawRequest: {
            locationId: string;
            /** Format: date */
            date: string;
            /** Format: date-time */
            timeSlotStart: string;
            /** Format: date-time */
            timeSlotEnd: string;
            reason: string;
        };
        TriggerDrawResponse: {
            drawAttemptId: string;
            status: string;
            /** Format: int32 */
            allocatedCount: number | string;
            /** Format: int32 */
            rejectedCount: number | string;
            /** Format: int32 */
            waitlistedCount: number | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
