// <auto-generated />
using System;
using FPS.DataHub.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FPS.DataHub.Infrastructure.Migrations
{
    [DbContext(typeof(DataHubDbContext))]
    [Migration("20260702142545_AddResourceTypeToBookingOutcome")]
    partial class AddResourceTypeToBookingOutcome
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FPS.DataHub.Domain.BookingOutcomeProjection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AllocationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AllocationSource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BookingRequestId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DrawAttemptId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FinalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RequestorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ResourceType")
                        .HasColumnType("text");

                    b.Property<string>("SafeReasonText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SlotId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("VehicleIsElectric")
                        .HasColumnType("boolean");

                    b.Property<string>("VehicleLicensePlate")
                        .HasColumnType("text");

                    b.Property<string>("VehicleType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookingRequestId")
                        .IsUnique()
                        .HasDatabaseName("ux_booking_outcome_request_id");

                    b.HasIndex("DrawAttemptId")
                        .HasDatabaseName("ix_booking_outcome_draw_attempt");

                    b.HasIndex("TenantId", "LocationId", "Date")
                        .HasDatabaseName("ix_booking_outcome_tenant_location_date");

                    b.HasIndex("TenantId", "RequestorId", "Date")
                        .HasDatabaseName("ix_booking_outcome_tenant_requestor_date");

                    b.ToTable("datahub_booking_outcome", (string)null);
                });

            modelBuilder.Entity("FPS.DataHub.Domain.DrawHistoryProjection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AlgorithmVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("AllocatedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DrawAttemptId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LifecycleStepsJson")
                        .HasColumnType("text");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RejectedCount")
                        .HasColumnType("integer");

                    b.Property<string>("RunReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SafeFailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TriggerSource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TriggeredBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("WaitlistedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DrawAttemptId")
                        .IsUnique()
                        .HasDatabaseName("ux_draw_history_attempt_id");

                    b.HasIndex("TenantId", "CompletedAt")
                        .HasDatabaseName("ix_draw_history_tenant_completed");

                    b.HasIndex("TenantId", "LocationId", "Date", "TimeSlot")
                        .HasDatabaseName("ix_draw_history_tenant_location_date");

                    b.ToTable("datahub_draw_history", (string)null);
                });

            modelBuilder.Entity("FPS.DataHub.Domain.TenantUsageStatsProjection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ActiveRequestorCount")
                        .HasColumnType("integer");

                    b.Property<int>("AllocatedCount")
                        .HasColumnType("integer");

                    b.Property<int>("BookingRequestCount")
                        .HasColumnType("integer");

                    b.Property<int>("CancelledCount")
                        .HasColumnType("integer");

                    b.Property<int>("DrawRunCount")
                        .HasColumnType("integer");

                    b.Property<int>("ExpiredCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NoShowCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PeriodMonth")
                        .HasColumnType("date");

                    b.Property<int>("RejectedCount")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PeriodMonth")
                        .IsUnique()
                        .HasDatabaseName("ux_usage_stats_tenant_period");

                    b.ToTable("datahub_tenant_usage_stats", (string)null);
                });

            modelBuilder.Entity("FPS.DataHub.Infrastructure.EventInboxRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AggregateId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessingError")
                        .HasColumnType("text");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceService")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("SourceEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_event_inbox_source_event_id");

                    b.HasIndex("ProcessingStatus", "RetryCount")
                        .HasDatabaseName("ix_event_inbox_status_retry");

                    b.HasIndex("TenantId", "ProcessedAt")
                        .HasDatabaseName("ix_event_inbox_tenant_processed");

                    b.ToTable("datahub_event_inbox", (string)null);
                });

            modelBuilder.Entity("FPS.DataHub.Infrastructure.ProjectionCheckpoint", b =>
                {
                    b.Property<string>("ProjectionName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("EventCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastProcessedEventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ProjectionName");

                    b.ToTable("datahub_projection_checkpoint", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
