services:
  
  envoy-proxy:
    image: envoyproxy/envoy:v1.33.1  # Use a recent Envoy version
    ports:
      - "10000:10000"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml  # Mount Envoy configuration
    networks:
      - web

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    networks:
      - web

  whoami-dapr:
    image: "daprio/daprd:latest"
    command: [
      "./daprd",
      "-app-id", "whoami",
      "-app-port", "80", # whoami's HTTP port
      "-dapr-http-port", "3500", # Dapr's HTTP port
      "-components-path", "/components", 
      "-config", "/configuration/fps-config.yaml",
      "--log-level", "debug" # Enable debug logs
    ]
    volumes:
      - "./dapr/components:/components" 
      - "./dapr/configuration/:/configuration"
    depends_on:
      - whoami
    network_mode: "service:whoami"


  vault:
    image: hashicorp/vault:latest
    ports:
      - "8200:8200"    
    cap_add:
      - IPC_LOCK
    networks:
      - web
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
    volumes:
      - ./vault/config/vault-config.json:/vault/config/vault-config.json
      - vault_data:/vault/data
    # command: server -dev
    # Using -dev mode first for testing
    # Later you can switch back to:
    command: server -config=/vault/config/vault-config.json    

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    networks:
      - web
    

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8180:8080"
    networks:
      - web
    command: start-dev
    

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - web
    

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb_data:/data/db
    networks:
      - web
    

  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web
    

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
      - "14268:14268"
    networks:
      - web
    

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - web
    

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yaml'
      - '--storage.path=/alertmanager'
    networks:
      - web
    

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - web
    

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - web
    

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - web
    

volumes:
  minio_data:
  postgres_data:
  mongodb_data:
  prometheus_data:
  grafana_data:
  vault_data:

networks:
  web:
    name: fps_network
    external: true